{% set name = "chebfun" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chebpy/chebpy/archive/v{{ version }}.tar.gz
  sha256: ca5fad55f4d7ff492959b1db606e0a2542f7c0a82669bcb14a5830869503a1e4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.16
    - pyfftw >=0.11

test:
  imports:
    - chebpy

about:
  home: https://github.com/chebpy/chebpy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A Python implementation of Chebfun
  description: |
    chebpy is a Python implementation of the popular MATLAB package
    Chebfun <http://chebfun.org>, allowing for computing with functions
    to near machine precision. It relies on polynomial interpolation
    using Chebyshev points and, through FFTs, expansions in Chebyshev
    polynomials.
  doc_url: https://github.com/chebpy/chebpy
  dev_url: https://github.com/chebpy/chebpy

extra:
  recipe-maintainers:
    - janniklasrose
    - markrichardson
