{% set name = "chebfun" %}
{% set version = "0.10.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chebpy/chebpy/archive/v{{ version }}.tar.gz
  sha256: b7a066c06d26825cb1031ed7394026ccfa6d98e417710fe16bdd9ee3e6644132

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - numpy >=2.4.1
    - matplotlib-base >=3.10.0

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - chebpy
  commands:
    - pip check
    - python -c "import importlib.metadata; assert importlib.metadata.version('chebfun') == '{{ version }}'"

about:
  home: https://github.com/chebpy/chebpy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A Python implementation of Chebfun
  description: |
    chebpy is a Python implementation of the popular MATLAB package
    Chebfun <http://chebfun.org>, allowing for computing with functions
    to near machine precision. It relies on polynomial interpolation
    using Chebyshev points and, through FFTs, expansions in Chebyshev
    polynomials.
  doc_url: https://github.com/chebpy/chebpy
  dev_url: https://github.com/chebpy/chebpy

extra:
  recipe-maintainers:
    - janniklasrose
    - markrichardson
